endpoint = {
    # canada
    1: ["https://www.opentable.ca/nova-scotia-new-brunswick-restaurant-listings",
        "https://www.opentable.ca/calgary-alberta-restaurant-listings",
        "https://www.opentable.ca/edmonton-alberta-restaurant-listings",
        "https://www.opentable.ca/manitoba-saskatchewan-restaurant-listings",
        "https://www.opentable.ca/montreal-quebec-restaurant-listings",
        "https://www.opentable.ca/rest_list.aspx?m=406",
        "https://www.opentable.ca/rest_list.aspx?m=451",
        "https://www.opentable.ca/toronto-ontario-restaurant-listings",
        "https://www.opentable.ca/vancouver-british-columbia-restaurant-listings",
        "https://www.opentable.ca/rest_list.aspx?m=3369"
        ],
    # germany
    2: [
        "https://www.opentable.ca/rest_list.aspx?m=3287",
        "https://www.opentable.ca/berlin-restaurant-listings",
        "https://www.opentable.ca/rest_list.aspx?m=3236",
        "https://www.opentable.ca/rest_list.aspx?m=3296",
        "https://www.opentable.ca/rest_list.aspx?m=3269",
        "https://www.opentable.ca/rest_list.aspx?m=236",
        "https://www.opentable.ca/rest_list.aspx?m=3293",
        "https://www.opentable.ca/rest_list.aspx?m=230",
        "https://www.opentable.ca/rest_list.aspx?m=233",
        "https://www.opentable.ca/rest_list.aspx?m=296",
        "https://www.opentable.ca/rest_list.aspx?m=3233",
        "https://www.opentable.ca/rest_list.aspx?m=3251",
        "https://www.opentable.ca/rest_list.aspx?m=293",
        "https://www.opentable.ca/rest_list.aspx?m=287",
        "https://www.opentable.ca/rest_list.aspx?m=3272",
        "https://www.opentable.ca/munich-restaurant-listings",
        "https://www.opentable.ca/rest_list.aspx?m=3275",
        "https://www.opentable.ca/rest_list.aspx?m=3239",
        "https://www.opentable.ca/rest_list.aspx?m=290",
        "https://www.opentable.ca/rest_list.aspx?m=3278",
        "https://www.opentable.ca/rest_list.aspx?m=3242",
        "https://www.opentable.ca/rest_list.aspx?m=3245",
        "https://www.opentable.ca/rest_list.aspx?m=3284",
        "https://www.opentable.ca/rest_list.aspx?m=3248",
        "https://www.opentable.ca/rest_list.aspx?m=242",
        "https://www.opentable.ca/rest_list.aspx?m=3260"
    ],
    # mexico
    3: [
        "https://www.opentable.ca/rest_list.aspx?m=358",
        "https://www.opentable.ca/s/restaurantlist?metroid=3374",
        "https://www.opentable.ca/rest_list.aspx?m=310",
        "https://www.opentable.ca/los-cabos-mexico-restaurant-listings",
        "https://www.opentable.ca/rest_list.aspx?m=502",
        "https://www.opentable.ca/rest_list.aspx?m=346",
        "https://www.opentable.ca/s/restaurantlist?metroid=499",
        "https://www.opentable.ca/rest_list.aspx?m=334",
        "https://www.opentable.ca/rest_list.aspx?m=475",
        "https://www.opentable.ca/rest_list.aspx?m=3400",
        "https://www.opentable.ca/s/restaurantlist?metroid=490",
        "https://www.opentable.ca/rest_list.aspx?m=349",
        "https://www.opentable.ca/rest_list.aspx?m=442",
        "https://www.opentable.ca/s/restaurantlist?metroid=3385",
        "https://www.opentable.ca/mexico-city-mexico-restaurant-listings",
        "https://www.opentable.ca/s/restaurantlist?metroid=3383",
        "https://www.opentable.ca/rest_list.aspx?m=355",
        "https://www.opentable.ca/s/restaurantlist?metroid=3370",
        "https://www.opentable.ca/s/restaurantlist?metroid=3486",
        "https://www.opentable.ca/rest_list.aspx?m=478",
        "https://www.opentable.ca/rest_list.aspx?m=361",
        "https://www.opentable.ca/puerto-vallarta-mexico-restaurant-listings",
        "https://www.opentable.ca/rest_list.aspx?m=457",
        "https://www.opentable.ca/rest_list.aspx?m=460",
        "https://www.opentable.ca/s/restaurantlist?metroid=508",
        "https://www.opentable.ca/rest_list.aspx?m=352",
        "https://www.opentable.ca/rest_list.aspx?m=472",
        "https://www.opentable.ca/rest_list.aspx?m=3443",
        "https://www.opentable.ca/s/restaurantlist?metroid=3437",
        "https://www.opentable.ca/rest_list.aspx?m=364",
        "https://www.opentable.ca/s/restaurantlist?metroid=505",
        "https://www.opentable.ca/rest_list.aspx?m=493"
    ]
}
